import { mysqlTable, index, primaryKey, int, varchar, unique, tinyint, longtext, decimal, char, datetime } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const fccLicenseAm = mysqlTable("fcc_license_am", {
	recordType: char("record_type", { length: 2 }).notNull(),
	uniqueSystemIdentifier: decimal("unique_system_identifier", { precision: 9, scale: 0 }).notNull(),
	ulsFileNum: char("uls_file_num", { length: 14 }),
	ebfNumber: varchar("ebf_number", { length: 30 }),
	callsign: char({ length: 10 }),
	operatorClass: char("operator_class", { length: 1 }),
	groupCode: char("group_code", { length: 1 }),
	regionCode: tinyint("region_code"),
	trusteeCallsign: char("trustee_callsign", { length: 10 }),
	trusteeIndicator: char("trustee_indicator", { length: 1 }),
	physicianCertification: char("physician_certification", { length: 1 }),
	veSignature: char("ve_signature", { length: 1 }),
	systematicCallsignChange: char("systematic_callsign_change", { length: 1 }),
	vanityCallsignChange: char("vanity_callsign_change", { length: 1 }),
	vanityRelationship: char("vanity_relationship", { length: 12 }),
	previousCallsign: char("previous_callsign", { length: 10 }),
	previousOperatorClass: char("previous_operator_class", { length: 1 }),
	trusteeName: varchar("trustee_name", { length: 50 }),
	rowHash: varchar("row_hash", { length: 40 }),
},
(table) => [
	primaryKey({ columns: [table.uniqueSystemIdentifier], name: "fcc_license_am_unique_system_identifier"}),
]);

export const fccLicenseEn = mysqlTable("fcc_license_en", {
	recordType: char("record_type", { length: 2 }).notNull(),
	uniqueSystemIdentifier: decimal("unique_system_identifier", { precision: 9, scale: 0 }).notNull(),
	ulsFileNumber: char("uls_file_number", { length: 14 }),
	ebfNumber: varchar("ebf_number", { length: 30 }),
	callSign: char("call_sign", { length: 10 }),
	entityType: char("entity_type", { length: 2 }),
	licenseeId: char("licensee_id", { length: 9 }),
	entityName: varchar("entity_name", { length: 200 }),
	firstName: varchar("first_name", { length: 20 }),
	mi: char({ length: 1 }),
	lastName: varchar("last_name", { length: 20 }),
	suffix: char({ length: 3 }),
	phone: char({ length: 10 }),
	fax: char({ length: 10 }),
	email: varchar({ length: 50 }),
	streetAddress: varchar("street_address", { length: 82 }),
	city: varchar({ length: 20 }),
	state: char({ length: 2 }),
	zipCode: char("zip_code", { length: 10 }),
	poBox: varchar("po_box", { length: 20 }),
	attentionLine: varchar("attention_line", { length: 35 }),
	sgin: char({ length: 3 }),
	frn: char({ length: 10 }),
	applicantTypeCode: char("applicant_type_code", { length: 1 }),
	applicantTypeOther: char("applicant_type_other", { length: 40 }),
	statusCode: char("status_code", { length: 1 }),
	statusDate: char("status_date", { length: 10 }),
	rowHash: varchar("row_hash", { length: 40 }),
	addressHash: varchar("address_hash", { length: 40 }),
},
(table) => [
	index("address_hash").on(table.addressHash),
	primaryKey({ columns: [table.uniqueSystemIdentifier], name: "fcc_license_en_unique_system_identifier"}),
]);

export const fccLicenseHd = mysqlTable("fcc_license_hd", {
	recordType: char("record_type", { length: 2 }).notNull(),
	uniqueSystemIdentifier: decimal("unique_system_identifier", { precision: 9, scale: 0 }).notNull(),
	ulsFileNumber: char("uls_file_number", { length: 14 }),
	ebfNumber: varchar("ebf_number", { length: 30 }),
	callSign: char("call_sign", { length: 10 }),
	licenseStatus: char("license_status", { length: 1 }),
	radioServiceCode: char("radio_service_code", { length: 2 }),
	grantDate: char("grant_date", { length: 10 }),
	expiredDate: char("expired_date", { length: 10 }),
	cancellationDate: char("cancellation_date", { length: 10 }),
	eligibilityRuleNum: char("eligibility_rule_num", { length: 10 }),
	applicantTypeCodeReserved: char("applicant_type_code_reserved", { length: 1 }),
	alien: char({ length: 1 }),
	alienGovernment: char("alien_government", { length: 1 }),
	alienCorporation: char("alien_corporation", { length: 1 }),
	alienOfficer: char("alien_officer", { length: 1 }),
	alienControl: char("alien_control", { length: 1 }),
	revoked: char({ length: 1 }),
	convicted: char({ length: 1 }),
	adjudged: char({ length: 1 }),
	involvedReserved: char("involved_reserved", { length: 1 }),
	commonCarrier: char("common_carrier", { length: 1 }),
	nonCommonCarrier: char("non_common_carrier", { length: 1 }),
	privateComm: char("private_comm", { length: 1 }),
	fixed: char({ length: 1 }),
	mobile: char({ length: 1 }),
	radiolocation: char({ length: 1 }),
	satellite: char({ length: 1 }),
	developmentalOrSta: char("developmental_or_sta", { length: 1 }),
	interconnectedService: char("interconnected_service", { length: 1 }),
	certifierFirstName: varchar("certifier_first_name", { length: 20 }),
	certifierMi: char("certifier_mi", { length: 1 }),
	certifierLastName: varchar("certifier_last_name", { length: 20 }),
	certifierSuffix: char("certifier_suffix", { length: 3 }),
	certifierTitle: char("certifier_title", { length: 40 }),
	gender: char({ length: 1 }),
	africanAmerican: char("african_american", { length: 1 }),
	nativeAmerican: char("native_american", { length: 1 }),
	hawaiian: char({ length: 1 }),
	asian: char({ length: 1 }),
	white: char({ length: 1 }),
	ethnicity: char({ length: 1 }),
	effectiveDate: char("effective_date", { length: 10 }),
	lastActionDate: char("last_action_date", { length: 10 }),
	auctionId: int("auction_id"),
	regStatBroadServ: char("reg_stat_broad_serv", { length: 1 }),
	bandManager: char("band_manager", { length: 1 }),
	typeServBroadServ: char("type_serv_broad_serv", { length: 1 }),
	alienRuling: char("alien_ruling", { length: 1 }),
	licenseeNameChange: char("licensee_name_change", { length: 1 }),
	rowHash: varchar("row_hash", { length: 40 }),
	totalHash: varchar("total_hash", { length: 40 }),
},
(table) => [
	index("call_sign").on(table.callSign),
	primaryKey({ columns: [table.uniqueSystemIdentifier], name: "fcc_license_hd_unique_system_identifier"}),
]);

export const hamAddress = mysqlTable("ham_address", {
	id: int({ unsigned: true }).autoincrement().notNull(),
	uuid: varchar({ length: 128 }).notNull(),
	langcode: varchar({ length: 12 }).notNull(),
	hash: varchar({ length: 40 }),
	addressLangcode: varchar("address__langcode", { length: 32 }),
	addressCountryCode: varchar("address__country_code", { length: 2 }),
	addressAdministrativeArea: varchar("address__administrative_area", { length: 255 }),
	addressLocality: varchar("address__locality", { length: 255 }),
	addressDependentLocality: varchar("address__dependent_locality", { length: 255 }),
	addressPostalCode: varchar("address__postal_code", { length: 255 }),
	addressSortingCode: varchar("address__sorting_code", { length: 255 }),
	addressAddressLine1: varchar("address__address_line1", { length: 255 }),
	addressAddressLine2: varchar("address__address_line2", { length: 255 }),
	addressAddressLine3: varchar("address__address_line3", { length: 255 }),
	addressOrganization: varchar("address__organization", { length: 255 }),
	addressGivenName: varchar("address__given_name", { length: 255 }),
	addressAdditionalName: varchar("address__additional_name", { length: 255 }),
	addressFamilyName: varchar("address__family_name", { length: 255 }),
	geocodeProvider: varchar("geocode_provider", { length: 2 }),
	geocodeStatus: int("geocode_status"),
	geocodeResponse: longtext("geocode_response"),
	locationId: int("location_id", { unsigned: true }),
	osmGeocodeStatus: int("osm_geocode_status"),
	osmGeocodeResponse: longtext("osm_geocode_response"),
	osmLatitude: decimal("osm_latitude", { precision: 10, scale: 7 }),
	osmLongitude: decimal("osm_longitude", { precision: 10, scale: 7 }),
	userId: int("user_id", { unsigned: true }).notNull(),
	status: tinyint().notNull(),
	created: int(),
	changed: int(),
	geocodeTime: int("geocode_time"),
	geocodePriority: int("geocode_priority"),
},
(table) => [
	index("ham_address_field__geocode_status__value").on(table.geocodeStatus),
	index("ham_address_field__location_id__target_id").on(table.locationId),
	index("ham_address_field__osm_geocode_status__value").on(table.osmGeocodeStatus),
	index("ham_address_field__user_id__target_id").on(table.userId),
	primaryKey({ columns: [table.id], name: "ham_address_id"}),
	unique("ham_address_field__hash").on(table.hash),
	unique("ham_address_field__uuid__value").on(table.uuid),
]);

export const hamLocation = mysqlTable("ham_location", {
	id: int({ unsigned: true }).autoincrement().notNull(),
	uuid: varchar({ length: 128 }).notNull(),
	langcode: varchar({ length: 12 }).notNull(),
	userId: int("user_id", { unsigned: true }).notNull(),
	latitude: decimal({ precision: 10, scale: 7 }),
	longitude: decimal({ precision: 10, scale: 7 }),
	status: tinyint().notNull(),
	created: int(),
	changed: int(),
},
(table) => [
	index("ham_location_field__user_id__target_id").on(table.userId),
	primaryKey({ columns: [table.id], name: "ham_location_id"}),
	unique("ham_location__latlng").on(table.latitude, table.longitude),
	unique("ham_location_field__uuid__value").on(table.uuid),
]);

export const hamStation = mysqlTable("ham_station", {
	id: int({ unsigned: true }).autoincrement().notNull(),
	uuid: varchar({ length: 128 }).notNull(),
	langcode: varchar({ length: 12 }).notNull(),
	callsign: varchar({ length: 20 }).notNull(),
	firstName: varchar("first_name", { length: 255 }),
	middleName: varchar("middle_name", { length: 255 }),
	lastName: varchar("last_name", { length: 255 }),
	suffix: varchar({ length: 3 }),
	organization: varchar({ length: 255 }),
	operatorClass: varchar("operator_class", { length: 1 }),
	previousCallsign: varchar("previous_callsign", { length: 20 }),
	totalHash: varchar("total_hash", { length: 40 }),
	addressHash: varchar("address_hash", { length: 40 }).notNull(),
	userId: int("user_id", { unsigned: true }).notNull(),
	status: tinyint().notNull(),
	created: int(),
	changed: int(),
},
(table) => [
	index("ham_station_field__address_hash").on(table.addressHash),
	index("ham_station_field__callsign").on(table.callsign),
	index("ham_station_field__user_id__target_id").on(table.userId),
	primaryKey({ columns: [table.id], name: "ham_station_id"}),
	unique("ham_station_field__uuid__value").on(table.uuid),
]);

export const appUsers = mysqlTable("app_users", {
	id: int({ unsigned: true }).autoincrement().notNull(),
	email: varchar({ length: 254 }).notNull(),
	createdAt: datetime("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	primaryKey({ columns: [table.id], name: "app_users_id" }),
	unique("app_users_email").on(table.email),
]);

export const magicLinkTokens = mysqlTable("magic_link_tokens", {
	id: int({ unsigned: true }).autoincrement().notNull(),
	email: varchar({ length: 254 }).notNull(),
	token: varchar({ length: 64 }).notNull(),
	expiresAt: datetime("expires_at").notNull(),
	usedAt: datetime("used_at"),
	createdAt: datetime("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
}, (table) => [
	primaryKey({ columns: [table.id], name: "magic_link_tokens_id" }),
	unique("magic_link_tokens_token").on(table.token),
	index("magic_link_tokens_email").on(table.email),
]);

export const exportQueue = mysqlTable("export_queue", {
	id: int({ unsigned: true }).autoincrement().notNull(),
	email: varchar({ length: 254 }).notNull(),
	state: varchar({ length: 2 }),
	zip: varchar({ length: 5 }),
	delimiter: varchar({ length: 1 }).notNull(),
	enclosure: varchar({ length: 1 }).notNull(),
	status: int().notNull().default(0),
	fileName: varchar("file_name", { length: 255 }),
	createdAt: datetime("created_at").default(sql`CURRENT_TIMESTAMP`).notNull(),
	startedAt: datetime("started_at"),
	processedAt: datetime("processed_at"),
}, (table) => [
	primaryKey({ columns: [table.id], name: "export_queue_id" }),
	index("export_queue_status").on(table.status),
	index("export_queue_email").on(table.email),
]);
